risk_alert:
  conflict_scores:
    life:
      total_luck: -8
      career: -6
      wealth: -6
      romance: -2
      health: -6
    fortune:
      total_luck: -2
      romance: -2
      health: -2
    travel:
      total_luck: -3
      career: -1
    career:
      total_luck: -3
      career: -8
      wealth: -3
    wealth:
      total_luck: -3
      career: -4
      wealth: -8
    spouse:
      total_luck: -1
      romance: -6
    health:
      total_luck: -2
      wealth: -1
      romance: -2
      health: -8
    property:
      total_luck: -1
      wealth: -3
    social:
      total_luck: -1
      career: -2
      wealth: -1
      romance: -2
    children:
      romance: -2
    parents:
      total_luck: -1
    siblings:
      career: -1
      wealth: -1
