import type { LifeScriptRules, NormalizedLifeScriptInput } from "./types";

export function createTestRules(): LifeScriptRules {
  return {
    dimension_weights: {
      total_luck: {
        main: { life: 0.5 },
        support: { fortune: 0.18, travel: 0.12 },
        triad_reference: "life",
        triad_weight: 0.15,
        body_weight: 0.05,
        module_caps: {
          major_star: 14,
          side_star: 6,
        },
        normalization: {
          min_raw: -8,
          max_raw: 22,
        },
      },
      career: {
        main: { career: 0.5 },
        support: { life: 0.1, travel: 0.1, social: 0.1 },
        triad_reference: "career",
        triad_weight: 0.15,
        body_weight: 0.05,
        module_caps: {
          major_star: 14,
          side_star: 6,
        },
        normalization: {
          min_raw: -10,
          max_raw: 24,
        },
      },
      wealth: {
        main: { wealth: 0.5 },
        support: { career: 0.1, fortune: 0.08, property: 0.12 },
        triad_reference: "wealth",
        triad_weight: 0.15,
        body_weight: 0.05,
        module_caps: {
          major_star: 14,
          side_star: 6,
        },
        normalization: {
          min_raw: -10,
          max_raw: 24,
        },
      },
      romance: {
        main: { spouse: 0.52 },
        support: { life: 0.1, fortune: 0.12, social: 0.06, children: 0.05 },
        triad_reference: "spouse",
        triad_weight: 0.1,
        body_weight: 0.05,
        module_caps: {
          major_star: 12,
          side_star: 5,
        },
        normalization: {
          min_raw: -9,
          max_raw: 22,
        },
      },
      health: {
        main: { health: 0.55 },
        support: { life: 0.1, fortune: 0.1, parents: 0.05 },
        triad_reference: "health",
        triad_weight: 0.15,
        body_weight: 0.05,
        module_caps: {
          major_star: 12,
          side_star: 5,
        },
        normalization: {
          min_raw: -9,
          max_raw: 22,
        },
      },
    },
    star_state_coeff: {
      temple: 1.25,
      prosperous: 1.12,
      neutral: 1,
      weak: 0.72,
    },
    star_base_scores: {
      wu_qu: {
        wealth: 9,
        career: 7,
        total_luck: 6,
        romance: 3,
        health: 4,
      },
      tai_yin: {
        wealth: 8,
        career: 4,
        total_luck: 7,
        romance: 7,
        health: 5,
      },
      tian_tong: {
        total_luck: 7,
        career: 2,
        wealth: 3,
        romance: 8,
        health: 6,
      },
      lian_zhen: {
        total_luck: 5,
        career: 7,
        wealth: 5,
        romance: 4,
        health: 3,
      },
      zi_wei: {
        total_luck: 10,
        career: 10,
        wealth: 6,
        romance: 4,
        health: 4,
      },
    },
    palace_affinity: {
      wu_qu: {
        wealth: 1.2,
        career: 1.15,
      },
      tai_yin: {
        wealth: 1.12,
        property: 1.18,
      },
      zi_wei: {
        life: 1.15,
      },
      wen_chang: {
        career: 1.1,
      },
      lu_cun: {
        wealth: 1.2,
      },
      tian_ma: {
        travel: 1.15,
        career: 1.08,
        wealth: 1.05,
      },
    },
    helper_stars: {
      wen_chang: { career: 4, wealth: 1, total_luck: 2 },
      lu_cun: { wealth: 6, total_luck: 4, career: 3, romance: 1, health: 1 },
      tian_ma: { wealth: 3, career: 3, total_luck: 2, romance: 1, health: 0 },
    },
    malefic_stars: {
      qing_yang: { romance: -3, health: -4, total_luck: -3, wealth: -2, career: -3 },
      di_kong: { wealth: -4, total_luck: -3, career: -3 },
    },
    changsheng: {
      帝旺: 3,
      衰: -1,
      病: -1,
      墓: -2,
      胎: 1,
      绝: -2,
    },
    misc_gods: {
      红鸾: { romance: 2 },
      病符: { health: -2, total_luck: -1 },
      破碎: { total_luck: -2, career: -2, wealth: -1, romance: -2, health: -1 },
      八座: { total_luck: 1, career: 2 },
    },
    transformations: {
      natal_scores: {
        lu: 3,
        quan: 2,
        ke: 2,
        ji: -3,
      },
      decade_scores: {
        lu: 6,
        quan: 3,
        ke: 3,
        ji: -6,
      },
    },
    risk_alert: {
      conflict_scores: {
        life: { total_luck: -8, career: -6, wealth: -6, romance: -2, health: -6 },
        wealth: { total_luck: -3, career: -4, wealth: -8 },
        spouse: { total_luck: -1, romance: -6 },
      },
    },
    body_adjustment: {
      relation_coeff: {
        main: 1,
        support: 0.7,
        triad: 0.5,
        weak_related: 0.3,
        none: 0,
      },
    },
    normalization: {
      display_min: 45,
      display_max: 100,
    },
    static_adjustment: {
      min: -5,
      max: 5,
    },
    summary_templates: {
      patterns: {
        rising_late: "先低后高",
        high_and_stable: "先高后稳",
        midlife_peak: "中年峰值",
        late_rise: "晚运抬升",
        volatile: "波动起伏",
        stable: "全程平稳",
      },
      current_period_templates: {
        high: "高位提示",
        middle: "中位提示",
        low: "低位提示",
      },
      dimension_brief_templates: {
        high: "{dimension_zh}-高",
        middle: "{dimension_zh}-中",
        low: "{dimension_zh}-低",
      },
    },
  };
}

export function createNormalizedInputForTests(): NormalizedLifeScriptInput {
  return {
    source: {},
    metadata: {},
    birth_year: 1984,
    body_palace_index: 0,
    static_palaces: [
      {
        index: 0,
        name_zh: "命宫",
        palace_key: "life",
        earthly_branch: "子",
        heavenly_stem: "丙",
        is_body_palace: true,
        major_stars: [
          {
            raw: "紫微(庙)",
            name_zh: "紫微",
            name_key: "zi_wei",
            state_zh: "庙",
            state_key: "temple",
            tags: [],
            natal_transformations: [],
          },
        ],
        helper_stars: [],
        malefic_stars: [],
        shensha: [],
        other_tags: [],
        changsheng_phase: "帝旺",
        misc_gods: {},
        relationships: {
          opposite_index: 6,
          wealth_trine_index: 8,
          career_trine_index: 4,
        },
      },
      {
        index: 4,
        name_zh: "财帛",
        palace_key: "wealth",
        earthly_branch: "辰",
        heavenly_stem: "甲",
        is_body_palace: false,
        major_stars: [
          {
            raw: "武曲(庙)-[生年科]",
            name_zh: "武曲",
            name_key: "wu_qu",
            state_zh: "庙",
            state_key: "temple",
            tags: ["生年科"],
            natal_transformations: [
              {
                tag: "生年科",
                effect_zh: "化科",
                effect_key: "ke",
              },
            ],
          },
        ],
        helper_stars: [
          {
            raw: "禄存",
            name_zh: "禄存",
            name_key: "lu_cun",
            state_zh: null,
            state_key: null,
            tags: [],
            natal_transformations: [],
          },
        ],
        malefic_stars: [],
        shensha: [],
        other_tags: [],
        changsheng_phase: "帝旺",
        misc_gods: {},
        relationships: {
          opposite_index: 10,
          wealth_trine_index: 0,
          career_trine_index: 8,
        },
      },
      {
        index: 6,
        name_zh: "迁移",
        palace_key: "travel",
        earthly_branch: "午",
        heavenly_stem: "丙",
        is_body_palace: false,
        major_stars: [],
        helper_stars: [
          {
            raw: "天马",
            name_zh: "天马",
            name_key: "tian_ma",
            state_zh: null,
            state_key: null,
            tags: [],
            natal_transformations: [],
          },
        ],
        malefic_stars: [],
        shensha: [],
        other_tags: [],
        changsheng_phase: "胎",
        misc_gods: {},
        relationships: {
          opposite_index: 0,
          wealth_trine_index: 2,
          career_trine_index: 10,
        },
      },
      {
        index: 8,
        name_zh: "官禄",
        palace_key: "career",
        earthly_branch: "申",
        heavenly_stem: "庚",
        is_body_palace: false,
        major_stars: [
          {
            raw: "太阴(旺)",
            name_zh: "太阴",
            name_key: "tai_yin",
            state_zh: "旺",
            state_key: "prosperous",
            tags: [],
            natal_transformations: [],
          },
        ],
        helper_stars: [
          {
            raw: "文昌",
            name_zh: "文昌",
            name_key: "wen_chang",
            state_zh: null,
            state_key: null,
            tags: [],
            natal_transformations: [],
          },
        ],
        malefic_stars: [
          {
            raw: "地空",
            name_zh: "地空",
            name_key: "di_kong",
            state_zh: null,
            state_key: null,
            tags: [],
            natal_transformations: [],
          },
        ],
        shensha: [],
        other_tags: [],
        changsheng_phase: "衰",
        misc_gods: {},
        relationships: {
          opposite_index: 2,
          wealth_trine_index: 4,
          career_trine_index: 0,
        },
      },
    ],
    decades: [
      {
        decade_index: 0,
        label: "2~11",
        start_age: 2,
        end_age: 11,
        target_year: 1986,
        stem: "丙",
        branch: "子",
        mapping: {
          life: 0,
          siblings: null,
          spouse: null,
          children: null,
          wealth: 4,
          health: null,
          travel: 6,
          social: null,
          career: 8,
          property: null,
          fortune: null,
          parents: null,
        },
        transformations: [
          {
            raw: "武曲化忌",
            star_zh: "武曲",
            star_key: "wu_qu",
            effect_zh: "化忌",
            effect_key: "ji",
          },
          {
            raw: "太阴化禄",
            star_zh: "太阴",
            star_key: "tai_yin",
            effect_zh: "化禄",
            effect_key: "lu",
          },
        ],
        risk_alert: {
          raw: "武曲-大限化忌 入 本命财帛 冲 本命命宫",
          star_zh: "武曲",
          star_key: "wu_qu",
          effect_zh: "化忌",
          effect_key: "ji",
          enter_palace_zh: "财帛",
          enter_palace_key: "wealth",
          conflict_palace_zh: "命宫",
          conflict_palace_key: "life",
        },
      },
      {
        decade_index: 1,
        label: "12~21",
        start_age: 12,
        end_age: 21,
        target_year: 1996,
        stem: "乙",
        branch: "亥",
        mapping: {
          life: 0,
          siblings: null,
          spouse: null,
          children: null,
          wealth: 4,
          health: null,
          travel: 6,
          social: null,
          career: 8,
          property: null,
          fortune: null,
          parents: null,
        },
        transformations: [],
        risk_alert: null,
      },
    ],
    debug: {
      normalization_warnings: [],
      natal_transformation_parse_notes: [],
    },
  };
}
